// <auto-generated />
using System;
using CRS_INTERN_PROJECT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRS_INTERN_PROJECT.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813183603_AddTenantApprovalStatus")]
    partial class AddTenantApprovalStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.ConsumerLoyalty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumerProfileId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPoints")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalReceiptCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ConsumerProfileId");

                    b.ToTable("ConsumerLoyalties");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.ConsumerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("IncomeLevel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("ConsumerProfiles");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.CorporateProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("CorporateProfiles");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConsumerProfileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ConsumerProfileId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.ReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ProductCategory")
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptItems");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionTier")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.ConsumerLoyalty", b =>
                {
                    b.HasOne("CRS_INTERN_PROJECT.Entities.Brand", "Brand")
                        .WithMany("Loyalties")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRS_INTERN_PROJECT.Entities.ConsumerProfile", "ConsumerProfile")
                        .WithMany("Loyalties")
                        .HasForeignKey("ConsumerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("ConsumerProfile");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.ConsumerProfile", b =>
                {
                    b.HasOne("CRS_INTERN_PROJECT.Entities.AppUser", "AppUser")
                        .WithOne("ConsumerProfile")
                        .HasForeignKey("CRS_INTERN_PROJECT.Entities.ConsumerProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.CorporateProfile", b =>
                {
                    b.HasOne("CRS_INTERN_PROJECT.Entities.AppUser", "AppUser")
                        .WithOne("CorporateProfile")
                        .HasForeignKey("CRS_INTERN_PROJECT.Entities.CorporateProfile", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRS_INTERN_PROJECT.Entities.Tenant", "Tenant")
                        .WithMany("CorporateUsers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Receipt", b =>
                {
                    b.HasOne("CRS_INTERN_PROJECT.Entities.Brand", "Brand")
                        .WithMany("Receipts")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRS_INTERN_PROJECT.Entities.ConsumerProfile", "ConsumerProfile")
                        .WithMany("Receipts")
                        .HasForeignKey("ConsumerProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");

                    b.Navigation("ConsumerProfile");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.ReceiptItem", b =>
                {
                    b.HasOne("CRS_INTERN_PROJECT.Entities.Receipt", "Receipt")
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.RefreshToken", b =>
                {
                    b.HasOne("CRS_INTERN_PROJECT.Entities.AppUser", "AppUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Tenant", b =>
                {
                    b.HasOne("CRS_INTERN_PROJECT.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.AppUser", b =>
                {
                    b.Navigation("ConsumerProfile");

                    b.Navigation("CorporateProfile");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Brand", b =>
                {
                    b.Navigation("Loyalties");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.ConsumerProfile", b =>
                {
                    b.Navigation("Loyalties");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Receipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("CRS_INTERN_PROJECT.Entities.Tenant", b =>
                {
                    b.Navigation("CorporateUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
